server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: catalog-service
          uri: http://localhost:8082
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
management:
  endpoints:
    web:
      exposure:
        include: health
security:
  jwt:
    secret: "CurrenWatches_SecretKey_SuperSegura_2024!!"